version: 0.2

env:
  variables:
    SONAR_URL: $SONAR_URL
    SONAR_PROJECT_KEY: $SONAR_PROJECT_KEY
    SONAR_LOGIN: $SONAR_LOGIN
    SONAR_TIMEOUT: $SONAR_TIMEOUT

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install # maven build command
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Code Static analysis started on `date`
      # - SONAR_TASK_ID=$(mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.ws.timeout=${SONAR_TIMEOUT} -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_LOGIN} | grep -E 'task\?id=[^ ]+' | cut -d'=' -f2)
      # - echo $SONAR_TASK_ID
      # - |
      #   if [ -z "$SONAR_TASK_ID" ];
      #   then
      #     echo "SonarQube analysis failed";
      #     exit 1;
      #   fi
      # - |
      #   stat="PENDING";
      #   while [ "$stat" != "SUCCESS" ]; do
      #     if [ $stat = "FAILED" ] || [ $stat = "CANCELLED" ]; then
      #       echo "SonarQube task ${SONAR_TASK_ID} failed";
      #       exit 1;
      #     fi
      #     stat=$(curl -u "${SONAR_LOGIN}:" ${SONAR_URL}/api/ce/task\?id=${SONAR_TASK_ID} | jq -r '.task.status');
      #     sleep 5;
      #   done
      # - SONAR_ANALYSIS_ID=$(curl -u "${SONAR_LOGIN}:" ${SONAR_URL}/api/ce/task\?id=${SONAR_TASK_ID} | jq -r '.task.analysisId')
      # - QUALITY_STATUS=$(curl -u "${SONAR_LOGIN}:" ${SONAR_URL}/api/qualitygates/project_status\?analysisId=${SONAR_ANALYSIS_ID} | jq -r '.projectStatus.status')
      # - |
      #   if [ ${QUALITY_STATUS} != "OK" ];
      #   then
      #     echo "in quality_status ERROR or WARN or Unexpected condition";
      #     exit 1;
      #   fi
      - echo Code Static analysis completed on `date`

cache:
  paths:
    - '/root/.m2/**/*'

artifacts: # build result configuration
  files:
    - target/demo-0.0.1-SNAPSHOT.jar # build result file name and path
    - appspec.yml # Spec for CodeDeploy
    - testspec.yml
    - scripts/* # Scripts for CodeDeploy
    - postman/*
  discard-paths: no
