version: 0.2

env:
  variables:
    LINTER_VERSION: $LINTER_VERSION

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - |
        # Check existing linter
        LINTER=`hadolint --version 2>/dev/null`
        # Set linter version
        if [[ -z "$LINTER_VERSION" || "$LINTER_VERSION" == "\$LINTER_VERSION" ]]; then
          LINTER_VERSION="v2.12.0"
        fi
        if [ -z "$LINTER" ]; then
          wget -cO - https://github.com/hadolint/hadolint/releases/download/${LINTER_VERSION}/hadolint-Linux-x86_64 > hadolint
          chmod +x hadolint
        fi

  build:
    commands:
      - ./hadolint ./Dockerfile -f json -c hadolint.yml > lint_result.json; EXITCODE=0

  post_build:
    commands:
      - |
        VALIDATE=`cat ./lint_result.json | grep '[E|e]rror'`
        if [ -n "$VALIDATE" ]; then
          echo "There is an error in dockerfile."
          exit 1
        fi
