#!/bin/bash
echo -e "version: 0.0\nResources:\n- TargetService:\n    Type: AWS::ECS::Service\n    Properties:\n      TaskDefinition: <TASK_DEFINITION>\n      LoadBalancerInfo:\n        ContainerName: \"$1\"\n        ContainerPort: $2" > $3/appspec.yaml
